apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-chart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- include "my-chart.helmAnnotations" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
