apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-chart.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
  annotations:
    {{- include "my-chart.helmAnnotations" . | nindent 4 }}
    {{- include "my-chart.dynamicIngressAnnotations" . | nindent 4 }}

spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hosts | first }}
      secretName: {{ include "my-chart.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.hosts | first }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "my-chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
